/*
 * In-memory database initialization.
 */
INSERT INTO sentiment_type(code, name) VALUES ('NEG', 'Negative');
INSERT INTO sentiment_type(code, name) VALUES ('NEU', 'Neutral');
INSERT INTO sentiment_type(code, name) VALUES ('POS', 'Positive');

INSERT INTO sentiment_lookup_domain(id, name) VALUES (1, 'Google');

INSERT INTO country(code, name) VALUES ('AF', 'Afghanistan');
INSERT INTO country(code, name) VALUES ('AL', 'Albania');
INSERT INTO country(code, name) VALUES ('DZ', 'Algeria');
INSERT INTO country(code, name) VALUES ('DS', 'American Samoa');
INSERT INTO country(code, name) VALUES ('AD', 'Andorra');
INSERT INTO country(code, name) VALUES ('AO', 'Angola');
INSERT INTO country(code, name) VALUES ('AI', 'Anguilla');
INSERT INTO country(code, name) VALUES ('AQ', 'Antarctica');
INSERT INTO country(code, name) VALUES ('AG', 'Antigua and Barbuda');
INSERT INTO country(code, name) VALUES ('AR', 'Argentina');
INSERT INTO country(code, name) VALUES ('AM', 'Armenia');
INSERT INTO country(code, name) VALUES ('AW', 'Aruba');
INSERT INTO country(code, name) VALUES ('AU', 'Australia');
INSERT INTO country(code, name) VALUES ('AT', 'Austria');
INSERT INTO country(code, name) VALUES ('AZ', 'Azerbaijan');
INSERT INTO country(code, name) VALUES ('BS', 'Bahamas');
INSERT INTO country(code, name) VALUES ('BH', 'Bahrain');
INSERT INTO country(code, name) VALUES ('BD', 'Bangladesh');
INSERT INTO country(code, name) VALUES ('BB', 'Barbados');
INSERT INTO country(code, name) VALUES ('BY', 'Belarus');
INSERT INTO country(code, name) VALUES ('BE', 'Belgium');
INSERT INTO country(code, name) VALUES ('BZ', 'Belize');
INSERT INTO country(code, name) VALUES ('BJ', 'Benin');
INSERT INTO country(code, name) VALUES ('BM', 'Bermuda');
INSERT INTO country(code, name) VALUES ('BT', 'Bhutan');
INSERT INTO country(code, name) VALUES ('BO', 'Bolivia');
INSERT INTO country(code, name) VALUES ('BA', 'Bosnia and Herzegovina');
INSERT INTO country(code, name) VALUES ('BW', 'Botswana');
INSERT INTO country(code, name) VALUES ('BV', 'Bouvet Island');
INSERT INTO country(code, name) VALUES ('BR', 'Brazil');
INSERT INTO country(code, name) VALUES ('IO', 'British Indian Ocean Territory');
INSERT INTO country(code, name) VALUES ('BN', 'Brunei Darussalam');
INSERT INTO country(code, name) VALUES ('BG', 'Bulgaria');
INSERT INTO country(code, name) VALUES ('BF', 'Burkina Faso');
INSERT INTO country(code, name) VALUES ('BI', 'Burundi');
INSERT INTO country(code, name) VALUES ('KH', 'Cambodia');
INSERT INTO country(code, name) VALUES ('CM', 'Cameroon');
INSERT INTO country(code, name) VALUES ('CA', 'Canada');
INSERT INTO country(code, name) VALUES ('CV', 'Cape Verde');
INSERT INTO country(code, name) VALUES ('KY', 'Cayman Islands');
INSERT INTO country(code, name) VALUES ('CF', 'Central African Republic');
INSERT INTO country(code, name) VALUES ('TD', 'Chad');
INSERT INTO country(code, name) VALUES ('CL', 'Chile');
INSERT INTO country(code, name) VALUES ('CN', 'China');
INSERT INTO country(code, name) VALUES ('CX', 'Christmas Island');
INSERT INTO country(code, name) VALUES ('CC', 'Cocos (Keeling) Islands');
INSERT INTO country(code, name) VALUES ('CO', 'Colombia');
INSERT INTO country(code, name) VALUES ('KM', 'Comoros');
INSERT INTO country(code, name) VALUES ('CG', 'Congo');
INSERT INTO country(code, name) VALUES ('CK', 'Cook Islands');
INSERT INTO country(code, name) VALUES ('CR', 'Costa Rica');
INSERT INTO country(code, name) VALUES ('HR', 'Croatia (Hrvatska)');
INSERT INTO country(code, name) VALUES ('CU', 'Cuba');
INSERT INTO country(code, name) VALUES ('CY', 'Cyprus');
INSERT INTO country(code, name) VALUES ('CZ', 'Czech Republic');
INSERT INTO country(code, name) VALUES ('DK', 'Denmark');
INSERT INTO country(code, name) VALUES ('DJ', 'Djibouti');
INSERT INTO country(code, name) VALUES ('DM', 'Dominica');
INSERT INTO country(code, name) VALUES ('DO', 'Dominican Republic');
INSERT INTO country(code, name) VALUES ('TP', 'East Timor');
INSERT INTO country(code, name) VALUES ('EC', 'Ecuador');
INSERT INTO country(code, name) VALUES ('EG', 'Egypt');
INSERT INTO country(code, name) VALUES ('SV', 'El Salvador');
INSERT INTO country(code, name) VALUES ('GQ', 'Equatorial Guinea');
INSERT INTO country(code, name) VALUES ('ER', 'Eritrea');
INSERT INTO country(code, name) VALUES ('EE', 'Estonia');
INSERT INTO country(code, name) VALUES ('ET', 'Ethiopia');
INSERT INTO country(code, name) VALUES ('FK', 'Falkland Islands (Malvinas)');
INSERT INTO country(code, name) VALUES ('FO', 'Faroe Islands');
INSERT INTO country(code, name) VALUES ('FJ', 'Fiji');
INSERT INTO country(code, name) VALUES ('FI', 'Finland');
INSERT INTO country(code, name) VALUES ('FR', 'France');
INSERT INTO country(code, name) VALUES ('FX', 'France, Metropolitan');
INSERT INTO country(code, name) VALUES ('GF', 'French Guiana');
INSERT INTO country(code, name) VALUES ('PF', 'French Polynesia');
INSERT INTO country(code, name) VALUES ('TF', 'French Southern Territories');
INSERT INTO country(code, name) VALUES ('GA', 'Gabon');
INSERT INTO country(code, name) VALUES ('GM', 'Gambia');
INSERT INTO country(code, name) VALUES ('GE', 'Georgia');
INSERT INTO country(code, name) VALUES ('DE', 'Germany');
INSERT INTO country(code, name) VALUES ('GH', 'Ghana');
INSERT INTO country(code, name) VALUES ('GI', 'Gibraltar');
INSERT INTO country(code, name) VALUES ('GK', 'Guernsey');
INSERT INTO country(code, name) VALUES ('GR', 'Greece');
INSERT INTO country(code, name) VALUES ('GL', 'Greenland');
INSERT INTO country(code, name) VALUES ('GD', 'Grenada');
INSERT INTO country(code, name) VALUES ('GP', 'Guadeloupe');
INSERT INTO country(code, name) VALUES ('GU', 'Guam');
INSERT INTO country(code, name) VALUES ('GT', 'Guatemala');
INSERT INTO country(code, name) VALUES ('GN', 'Guinea');
INSERT INTO country(code, name) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO country(code, name) VALUES ('GY', 'Guyana');
INSERT INTO country(code, name) VALUES ('HT', 'Haiti');
INSERT INTO country(code, name) VALUES ('HM', 'Heard and Mc Donald Islands');
INSERT INTO country(code, name) VALUES ('HN', 'Honduras');
INSERT INTO country(code, name) VALUES ('HK', 'Hong Kong');
INSERT INTO country(code, name) VALUES ('HU', 'Hungary');
INSERT INTO country(code, name) VALUES ('IS', 'Iceland');
INSERT INTO country(code, name) VALUES ('IN', 'India');
INSERT INTO country(code, name) VALUES ('IM', 'Isle of Man');
INSERT INTO country(code, name) VALUES ('ID', 'Indonesia');
INSERT INTO country(code, name) VALUES ('IR', 'Iran (Islamic Republic of)');
INSERT INTO country(code, name) VALUES ('IQ', 'Iraq');
INSERT INTO country(code, name) VALUES ('IE', 'Ireland');
INSERT INTO country(code, name) VALUES ('IL', 'Israel');
INSERT INTO country(code, name) VALUES ('IT', 'Italy');
INSERT INTO country(code, name) VALUES ('CI', 'Ivory Coast');
INSERT INTO country(code, name) VALUES ('JE', 'Jersey');
INSERT INTO country(code, name) VALUES ('JM', 'Jamaica');
INSERT INTO country(code, name) VALUES ('JP', 'Japan');
INSERT INTO country(code, name) VALUES ('JO', 'Jordan');
INSERT INTO country(code, name) VALUES ('KZ', 'Kazakhstan');
INSERT INTO country(code, name) VALUES ('KE', 'Kenya');
INSERT INTO country(code, name) VALUES ('KI', 'Kiribati');
INSERT INTO country(code, name) VALUES ('KP', 'Korea, Democratic People''s Republic of');
INSERT INTO country(code, name) VALUES ('KR', 'Korea, Republic of');
INSERT INTO country(code, name) VALUES ('XK', 'Kosovo');
INSERT INTO country(code, name) VALUES ('KW', 'Kuwait');
INSERT INTO country(code, name) VALUES ('KG', 'Kyrgyzstan');
INSERT INTO country(code, name) VALUES ('LA', 'Lao People''s Democratic Republic');
INSERT INTO country(code, name) VALUES ('LV', 'Latvia');
INSERT INTO country(code, name) VALUES ('LB', 'Lebanon');
INSERT INTO country(code, name) VALUES ('LS', 'Lesotho');
INSERT INTO country(code, name) VALUES ('LR', 'Liberia');
INSERT INTO country(code, name) VALUES ('LY', 'Libyan Arab Jamahiriya');
INSERT INTO country(code, name) VALUES ('LI', 'Liechtenstein');
INSERT INTO country(code, name) VALUES ('LT', 'Lithuania');
INSERT INTO country(code, name) VALUES ('LU', 'Luxembourg');
INSERT INTO country(code, name) VALUES ('MO', 'Macau');
INSERT INTO country(code, name) VALUES ('MK', 'Macedonia');
INSERT INTO country(code, name) VALUES ('MG', 'Madagascar');
INSERT INTO country(code, name) VALUES ('MW', 'Malawi');
INSERT INTO country(code, name) VALUES ('MY', 'Malaysia');
INSERT INTO country(code, name) VALUES ('MV', 'Maldives');
INSERT INTO country(code, name) VALUES ('ML', 'Mali');
INSERT INTO country(code, name) VALUES ('MT', 'Malta');
INSERT INTO country(code, name) VALUES ('MH', 'Marshall Islands');
INSERT INTO country(code, name) VALUES ('MQ', 'Martinique');
INSERT INTO country(code, name) VALUES ('MR', 'Mauritania');
INSERT INTO country(code, name) VALUES ('MU', 'Mauritius');
INSERT INTO country(code, name) VALUES ('TY', 'Mayotte');
INSERT INTO country(code, name) VALUES ('MX', 'Mexico');
INSERT INTO country(code, name) VALUES ('FM', 'Micronesia, Federated States of');
INSERT INTO country(code, name) VALUES ('MD', 'Moldova, Republic of');
INSERT INTO country(code, name) VALUES ('MC', 'Monaco');
INSERT INTO country(code, name) VALUES ('MN', 'Mongolia');
INSERT INTO country(code, name) VALUES ('ME', 'Montenegro');
INSERT INTO country(code, name) VALUES ('MS', 'Montserrat');
INSERT INTO country(code, name) VALUES ('MA', 'Morocco');
INSERT INTO country(code, name) VALUES ('MZ', 'Mozambique');
INSERT INTO country(code, name) VALUES ('MM', 'Myanmar');
INSERT INTO country(code, name) VALUES ('NA', 'Namibia');
INSERT INTO country(code, name) VALUES ('NR', 'Nauru');
INSERT INTO country(code, name) VALUES ('NP', 'Nepal');
INSERT INTO country(code, name) VALUES ('NL', 'Netherlands');
INSERT INTO country(code, name) VALUES ('AN', 'Netherlands Antilles');
INSERT INTO country(code, name) VALUES ('NC', 'New Caledonia');
INSERT INTO country(code, name) VALUES ('NZ', 'New Zealand');
INSERT INTO country(code, name) VALUES ('NI', 'Nicaragua');
INSERT INTO country(code, name) VALUES ('NE', 'Niger');
INSERT INTO country(code, name) VALUES ('NG', 'Nigeria');
INSERT INTO country(code, name) VALUES ('NU', 'Niue');
INSERT INTO country(code, name) VALUES ('NF', 'Norfolk Island');
INSERT INTO country(code, name) VALUES ('MP', 'Northern Mariana Islands');
INSERT INTO country(code, name) VALUES ('NO', 'Norway');
INSERT INTO country(code, name) VALUES ('OM', 'Oman');
INSERT INTO country(code, name) VALUES ('PK', 'Pakistan');
INSERT INTO country(code, name) VALUES ('PW', 'Palau');
INSERT INTO country(code, name) VALUES ('PS', 'Palestine');
INSERT INTO country(code, name) VALUES ('PA', 'Panama');
INSERT INTO country(code, name) VALUES ('PG', 'Papua New Guinea');
INSERT INTO country(code, name) VALUES ('PY', 'Paraguay');
INSERT INTO country(code, name) VALUES ('PE', 'Peru');
INSERT INTO country(code, name) VALUES ('PH', 'Philippines');
INSERT INTO country(code, name) VALUES ('PN', 'Pitcairn');
INSERT INTO country(code, name) VALUES ('PL', 'Poland');
INSERT INTO country(code, name) VALUES ('PT', 'Portugal');
INSERT INTO country(code, name) VALUES ('PR', 'Puerto Rico');
INSERT INTO country(code, name) VALUES ('QA', 'Qatar');
INSERT INTO country(code, name) VALUES ('RE', 'Reunion');
INSERT INTO country(code, name) VALUES ('RO', 'Romania');
INSERT INTO country(code, name) VALUES ('RU', 'Russian Federation');
INSERT INTO country(code, name) VALUES ('RW', 'Rwanda');
INSERT INTO country(code, name) VALUES ('KN', 'Saint Kitts and Nevis');
INSERT INTO country(code, name) VALUES ('LC', 'Saint Lucia');
INSERT INTO country(code, name) VALUES ('VC', 'Saint Vincent and the Grenadines');
INSERT INTO country(code, name) VALUES ('WS', 'Samoa');
INSERT INTO country(code, name) VALUES ('SM', 'San Marino');
INSERT INTO country(code, name) VALUES ('ST', 'Sao Tome and Principe');
INSERT INTO country(code, name) VALUES ('SA', 'Saudi Arabia');
INSERT INTO country(code, name) VALUES ('SN', 'Senegal');
INSERT INTO country(code, name) VALUES ('RS', 'Serbia');
INSERT INTO country(code, name) VALUES ('SC', 'Seychelles');
INSERT INTO country(code, name) VALUES ('SL', 'Sierra Leone');
INSERT INTO country(code, name) VALUES ('SG', 'Singapore');
INSERT INTO country(code, name) VALUES ('SK', 'Slovakia');
INSERT INTO country(code, name) VALUES ('SI', 'Slovenia');
INSERT INTO country(code, name) VALUES ('SB', 'Solomon Islands');
INSERT INTO country(code, name) VALUES ('SO', 'Somalia');
INSERT INTO country(code, name) VALUES ('ZA', 'South Africa');
INSERT INTO country(code, name) VALUES ('GS', 'South Georgia South Sandwich Islands');
INSERT INTO country(code, name) VALUES ('ES', 'Spain');
INSERT INTO country(code, name) VALUES ('LK', 'Sri Lanka');
INSERT INTO country(code, name) VALUES ('SH', 'St. Helena');
INSERT INTO country(code, name) VALUES ('PM', 'St. Pierre and Miquelon');
INSERT INTO country(code, name) VALUES ('SD', 'Sudan');
INSERT INTO country(code, name) VALUES ('SR', 'Suriname');
INSERT INTO country(code, name) VALUES ('SJ', 'Svalbard and Jan Mayen Islands');
INSERT INTO country(code, name) VALUES ('SZ', 'Swaziland');
INSERT INTO country(code, name) VALUES ('SE', 'Sweden');
INSERT INTO country(code, name) VALUES ('CH', 'Switzerland');
INSERT INTO country(code, name) VALUES ('SY', 'Syrian Arab Republic');
INSERT INTO country(code, name) VALUES ('TW', 'Taiwan');
INSERT INTO country(code, name) VALUES ('TJ', 'Tajikistan');
INSERT INTO country(code, name) VALUES ('TZ', 'Tanzania, United Republic of');
INSERT INTO country(code, name) VALUES ('TH', 'Thailand');
INSERT INTO country(code, name) VALUES ('TG', 'Togo');
INSERT INTO country(code, name) VALUES ('TK', 'Tokelau');
INSERT INTO country(code, name) VALUES ('TO', 'Tonga');
INSERT INTO country(code, name) VALUES ('TT', 'Trinidad and Tobago');
INSERT INTO country(code, name) VALUES ('TN', 'Tunisia');
INSERT INTO country(code, name) VALUES ('TR', 'Turkey');
INSERT INTO country(code, name) VALUES ('TM', 'Turkmenistan');
INSERT INTO country(code, name) VALUES ('TC', 'Turks and Caicos Islands');
INSERT INTO country(code, name) VALUES ('TV', 'Tuvalu');
INSERT INTO country(code, name) VALUES ('UG', 'Uganda');
INSERT INTO country(code, name) VALUES ('UA', 'Ukraine');
INSERT INTO country(code, name) VALUES ('AE', 'United Arab Emirates');
INSERT INTO country(code, name) VALUES ('GB', 'United Kingdom');
INSERT INTO country(code, name) VALUES ('US', 'United States');
INSERT INTO country(code, name) VALUES ('UM', 'United States minor outlying islands');
INSERT INTO country(code, name) VALUES ('UY', 'Uruguay');
INSERT INTO country(code, name) VALUES ('UZ', 'Uzbekistan');
INSERT INTO country(code, name) VALUES ('VU', 'Vanuatu');
INSERT INTO country(code, name) VALUES ('VA', 'Vatican City State');
INSERT INTO country(code, name) VALUES ('VE', 'Venezuela');
INSERT INTO country(code, name) VALUES ('VN', 'Vietnam');
INSERT INTO country(code, name) VALUES ('VG', 'Virgin Islands (British)');
INSERT INTO country(code, name) VALUES ('VI', 'Virgin Islands (U.S.)');
INSERT INTO country(code, name) VALUES ('WF', 'Wallis and Futuna Islands');
INSERT INTO country(code, name) VALUES ('EH', 'Western Sahara');
INSERT INTO country(code, name) VALUES ('YE', 'Yemen');
INSERT INTO country(code, name) VALUES ('ZR', 'Zaire');
INSERT INTO country(code, name) VALUES ('ZM', 'Zambia');
INSERT INTO country(code, name) VALUES ('ZW', 'Zimbabwe');

-- https://en.wikipedia.org/wiki/Thomson_Reuters_Business_Classification
INSERT INTO business_type(id, name) VALUES (1, 'Advanced Medical Equipment');
INSERT INTO business_type(id, name) VALUES (2, 'Advertising & Marketing');
INSERT INTO business_type(id, name) VALUES (3, 'Aerospace & Defense');
INSERT INTO business_type(id, name) VALUES (4, 'Agricultural Chemicals');
INSERT INTO business_type(id, name) VALUES (5, 'Air Freight & Courier Services');
INSERT INTO business_type(id, name) VALUES (6, 'Airlines');
INSERT INTO business_type(id, name) VALUES (7, 'Airport Services');
INSERT INTO business_type(id, name) VALUES (8, 'Aluminum');
INSERT INTO business_type(id, name) VALUES (9, 'Apparel & Accessories Retailers');
INSERT INTO business_type(id, name) VALUES (10, 'Apparel & Accessories');
INSERT INTO business_type(id, name) VALUES (11, 'Appliances, Tools & Housewares');
INSERT INTO business_type(id, name) VALUES (12, 'Auto & Truck Manufacturers');
INSERT INTO business_type(id, name) VALUES (13, 'Auto Vehicles, Parts & Service Retailers');
INSERT INTO business_type(id, name) VALUES (14, 'Auto, Truck & Motorcycle Parts');
INSERT INTO business_type(id, name) VALUES (15, 'Banks');
INSERT INTO business_type(id, name) VALUES (16, 'Biotechnology & Medical Research');
INSERT INTO business_type(id, name) VALUES (17, 'Brewers');
INSERT INTO business_type(id, name) VALUES (18, 'Broadcasting');
INSERT INTO business_type(id, name) VALUES (19, 'Business Support Services');
INSERT INTO business_type(id, name) VALUES (20, 'Business Support Supplies');
INSERT INTO business_type(id, name) VALUES (21, 'Casinos & Gaming');
INSERT INTO business_type(id, name) VALUES (22, 'Closed End Funds');
INSERT INTO business_type(id, name) VALUES (23, 'Coal');
INSERT INTO business_type(id, name) VALUES (24, 'Commercial Printing Services');
INSERT INTO business_type(id, name) VALUES (25, 'Commercial REITs');
INSERT INTO business_type(id, name) VALUES (26, 'Commodity Chemicals');
INSERT INTO business_type(id, name) VALUES (27, 'Communications Equipment');
INSERT INTO business_type(id, name) VALUES (28, 'Computer & Electronics Retailers');
INSERT INTO business_type(id, name) VALUES (29, 'Computer Hardware');
INSERT INTO business_type(id, name) VALUES (30, 'Construction & Engineering');
INSERT INTO business_type(id, name) VALUES (31, 'Construction Materials');
INSERT INTO business_type(id, name) VALUES (32, 'Construction Supplies & Fittings');
INSERT INTO business_type(id, name) VALUES (33, 'Consumer Electronics Discontinued');
INSERT INTO business_type(id, name) VALUES (34, 'Consumer Financial Services');
INSERT INTO business_type(id, name) VALUES (35, 'Consumer Publishing');
INSERT INTO business_type(id, name) VALUES (36, 'Corporate Financial Services');
INSERT INTO business_type(id, name) VALUES (37, 'Department Stores');
INSERT INTO business_type(id, name) VALUES (38, 'Discount Stores');
INSERT INTO business_type(id, name) VALUES (39, 'Distillers & Wineries');
INSERT INTO business_type(id, name) VALUES (40, 'Diversified Chemicals');
INSERT INTO business_type(id, name) VALUES (41, 'Diversified Financial Services Discontinued');
INSERT INTO business_type(id, name) VALUES (42, 'Diversified Investment Services');
INSERT INTO business_type(id, name) VALUES (43, 'Diversified Media Discontinued');
INSERT INTO business_type(id, name) VALUES (44, 'Diversified Pharmaceuticals Discontinued');
INSERT INTO business_type(id, name) VALUES (45, 'Diversified REITs');
INSERT INTO business_type(id, name) VALUES (46, 'Diversified Trading & Distributing');
INSERT INTO business_type(id, name) VALUES (47, 'Drug Retailers');
INSERT INTO business_type(id, name) VALUES (48, 'Electric Utilities');
INSERT INTO business_type(id, name) VALUES (49, 'Electrical Components & Equipment');
INSERT INTO business_type(id, name) VALUES (50, 'Electronic Equipments & Parts');
INSERT INTO business_type(id, name) VALUES (51, 'Employment Services');
INSERT INTO business_type(id, name) VALUES (52, 'Entertainment Production');
INSERT INTO business_type(id, name) VALUES (53, 'Environmental Services & Equipment');
INSERT INTO business_type(id, name) VALUES (54, 'Exchange Traded Funds');
INSERT INTO business_type(id, name) VALUES (55, 'Financial & Commodity Market Operators');
INSERT INTO business_type(id, name) VALUES (56, 'Fishing & Farming');
INSERT INTO business_type(id, name) VALUES (57, 'Food Distribution & Convenience Stores');
INSERT INTO business_type(id, name) VALUES (58, 'Food Processing');
INSERT INTO business_type(id, name) VALUES (59, 'Footwear');
INSERT INTO business_type(id, name) VALUES (60, 'Forest & Wood Products');
INSERT INTO business_type(id, name) VALUES (61, 'Generic & Specialty Pharmaceuticals Discontinued');
INSERT INTO business_type(id, name) VALUES (62, 'Gold');
INSERT INTO business_type(id, name) VALUES (63, 'Ground Freight & Logistics');
INSERT INTO business_type(id, name) VALUES (64, 'Healthcare Facilities & Services');
INSERT INTO business_type(id, name) VALUES (65, 'Heavy Electrical Equipment');
INSERT INTO business_type(id, name) VALUES (66, 'Heavy Machinery & Vehicles');
INSERT INTO business_type(id, name) VALUES (67, 'Highways & Rail Tracks');
INSERT INTO business_type(id, name) VALUES (68, 'Holding Companies');
INSERT INTO business_type(id, name) VALUES (69, 'Home Furnishing');
INSERT INTO business_type(id, name) VALUES (70, 'Home Furnishings Retailers');
INSERT INTO business_type(id, name) VALUES (71, 'Home Improvement Products & Services Retailers');
INSERT INTO business_type(id, name) VALUES (72, 'Homebuilding');
INSERT INTO business_type(id, name) VALUES (73, 'Hotels, Motels & Cruise Lines');
INSERT INTO business_type(id, name) VALUES (74, 'Household Electronics');
INSERT INTO business_type(id, name) VALUES (75, 'Household Products');
INSERT INTO business_type(id, name) VALUES (76, 'IT Services & Consulting');
INSERT INTO business_type(id, name) VALUES (77, 'Independent Power Producers');
INSERT INTO business_type(id, name) VALUES (78, 'Industrial Conglomerates');
INSERT INTO business_type(id, name) VALUES (79, 'Industrial Machinery & Equipment');
INSERT INTO business_type(id, name) VALUES (80, 'Insurance Brokers Discontinued');
INSERT INTO business_type(id, name) VALUES (81, 'Insurance Funds');
INSERT INTO business_type(id, name) VALUES (82, 'Integrated Mining');
INSERT INTO business_type(id, name) VALUES (83, 'Integrated Oil and gas');
INSERT INTO business_type(id, name) VALUES (84, 'Integrated Telecommunications Services');
INSERT INTO business_type(id, name) VALUES (85, 'Internet Services');
INSERT INTO business_type(id, name) VALUES (86, 'Investment Banking & Brokerage Services');
INSERT INTO business_type(id, name) VALUES (87, 'Investment Management & Fund Operators');
INSERT INTO business_type(id, name) VALUES (88, 'Investment Trusts');
INSERT INTO business_type(id, name) VALUES (89, 'Leisure & Recreation');
INSERT INTO business_type(id, name) VALUES (90, 'Life & Health Insurance');
INSERT INTO business_type(id, name) VALUES (91, 'Managed Healthcare');
INSERT INTO business_type(id, name) VALUES (92, 'Marine Freight & Logistics');
INSERT INTO business_type(id, name) VALUES (93, 'Marine Port Services');
INSERT INTO business_type(id, name) VALUES (94, 'Medical Equipment, Supplies & Distribution');
INSERT INTO business_type(id, name) VALUES (95, 'Mining Support Services & Equipment');
INSERT INTO business_type(id, name) VALUES (96, 'Miscellaneous Specialty Retailers');
INSERT INTO business_type(id, name) VALUES (97, 'Multiline Insurance');
INSERT INTO business_type(id, name) VALUES (98, 'Multiline Utilities');
INSERT INTO business_type(id, name) VALUES (99, 'Mutual Funds');
INSERT INTO business_type(id, name) VALUES (100, 'Natural Gas Utilities');
INSERT INTO business_type(id, name) VALUES (101, 'Non-Alcoholic Beverages');
INSERT INTO business_type(id, name) VALUES (102, 'Non-Paper Containers & Packaging');
INSERT INTO business_type(id, name) VALUES (103, 'Office Equipment');
INSERT INTO business_type(id, name) VALUES (104, 'Oil & Gas Drilling');
INSERT INTO business_type(id, name) VALUES (105, 'Oil & Gas Exploration and Production');
INSERT INTO business_type(id, name) VALUES (106, 'Oil & Gas Refining and Marketing');
INSERT INTO business_type(id, name) VALUES (107, 'Oil & Gas Transportation Services');
INSERT INTO business_type(id, name) VALUES (108, 'Oil-related Services and Equipment');
INSERT INTO business_type(id, name) VALUES (109, 'Paper Packaging');
INSERT INTO business_type(id, name) VALUES (110, 'Paper Products');
INSERT INTO business_type(id, name) VALUES (111, 'Passenger Transportation, Ground & Sea');
INSERT INTO business_type(id, name) VALUES (112, 'Pension Funds');
INSERT INTO business_type(id, name) VALUES (113, 'Personal Products');
INSERT INTO business_type(id, name) VALUES (114, 'Personal Services');
INSERT INTO business_type(id, name) VALUES (115, 'Pharmaceuticals');
INSERT INTO business_type(id, name) VALUES (116, 'Phones & Handheld Devices');
INSERT INTO business_type(id, name) VALUES (117, 'Precious metals & Minerals');
INSERT INTO business_type(id, name) VALUES (118, 'Professional Information Services');
INSERT INTO business_type(id, name) VALUES (119, 'Property & Casualty Insurance');
INSERT INTO business_type(id, name) VALUES (120, 'Real Estate Development & Operations');
INSERT INTO business_type(id, name) VALUES (121, 'Real Estate Services');
INSERT INTO business_type(id, name) VALUES (122, 'Recreational Products');
INSERT INTO business_type(id, name) VALUES (123, 'Reinsurance');
INSERT INTO business_type(id, name) VALUES (124, 'Renewable Energy Equipment & Services');
INSERT INTO business_type(id, name) VALUES (125, 'Renewable Fuels');
INSERT INTO business_type(id, name) VALUES (126, 'Residential REITs');
INSERT INTO business_type(id, name) VALUES (127, 'Restaurants & Bars');
INSERT INTO business_type(id, name) VALUES (128, 'Semiconductor Equipment & Testing');
INSERT INTO business_type(id, name) VALUES (129, 'Semiconductors');
INSERT INTO business_type(id, name) VALUES (130, 'Shipbuilding');
INSERT INTO business_type(id, name) VALUES (131, 'Software');
INSERT INTO business_type(id, name) VALUES (132, 'Specialized REITs');
INSERT INTO business_type(id, name) VALUES (133, 'Specialty Chemicals');
INSERT INTO business_type(id, name) VALUES (134, 'Specialty Investment Services Discontinued');
INSERT INTO business_type(id, name) VALUES (135, 'Specialty Mining & Metals');
INSERT INTO business_type(id, name) VALUES (136, 'Steel');
INSERT INTO business_type(id, name) VALUES (137, 'Textiles & Leather Goods');
INSERT INTO business_type(id, name) VALUES (138, 'Tires & Rubber Products');
INSERT INTO business_type(id, name) VALUES (139, 'Tobacco');
INSERT INTO business_type(id, name) VALUES (140, 'Toys & Juvenile Products');
INSERT INTO business_type(id, name) VALUES (141, 'Uranium');
INSERT INTO business_type(id, name) VALUES (142, 'Water & Other Utilities');
INSERT INTO business_type(id, name) VALUES (143, 'Wireless Telecommunications Services');
